FIND_PATH(COLLECTC_INCLUDE_DIR collectc/list.h)
FIND_LIBRARY(COLLECTC_LIBRARY NAMES collectc)

# Handle the QUIETLY and REQUIRED arguments and set COLLECTC_FOUND to TRUE if all listed variables are TRUE.
INCLUDE(FindPackageHandleStandardArgs)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(COLLECTC REQUIRED_VARS COLLECTC_LIBRARY COLLECTC_INCLUDE_DIR)

# Copy the results to the output variables.
if (COLLECTC_FOUND)
    SET(COLLECTC_LIBRARIES ${COLLECTC_LIBRARY})
    SET(COLLECTC_INCLUDE_DIRS ${COLLECTC_INCLUDE_DIR})
    if (NOT TARGET COLLECTC::COLLECTC)
        add_library(COLLECTC::COLLECTC UNKNOWN IMPORTED)
        set_target_properties(COLLECTC::COLLECTC PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${COLLECTC_INCLUDE_DIR}")
        set_property(TARGET COLLECTC::COLLECTC APPEND PROPERTY IMPORTED_LOCATION "${COLLECTC_LIBRARY}")
    endif ()
else (COLLECTC_FOUND)
    SET(COLLECTC_LIBRARIES)
    SET(COLLECTC_INCLUDE_DIRS)
endif (COLLECTC_FOUND)
MARK_AS_ADVANCED(COLLECTC_INCLUDE_DIRS COLLECTC_LIBRARIES)