function(rox_add_tests FILE_EXT LIBS)
    set(TEST_DIR ${CMAKE_CURRENT_SOURCE_DIR}/${ARGN})
    file(GLOB children RELATIVE ${TEST_DIR} ${TEST_DIR}/*)
    message("Adding tests from ${TEST_DIR}")
    if (ARGN)
        set(TEST_PATH ${ARGN}/)
    else ()
        set(TEST_PATH "")
    endif ()
    foreach (child ${children})
        if (IS_DIRECTORY ${TEST_DIR}/${child})
            rox_add_tests("${FILE_EXT}" "${LIBS}" "${TEST_PATH}${child}")
        else ()
            get_filename_component(TEST_FILE_EXT ${child} EXT)
            if ("${TEST_FILE_EXT}" STREQUAL ${FILE_EXT})
                get_filename_component(TEST_NAME ${child} NAME_WE)
                add_executable(${TEST_NAME} ${TEST_PATH}${child})
                add_test(${TEST_NAME} ${CMAKE_CURRENT_BINARY_DIR}/${TEST_PATH}${TEST_NAME})
                target_link_libraries(${TEST_NAME} ${LIBS})
            endif ()
        endif ()
    endforeach ()
endfunction()